{"name": "test_1", "status": "skipped", "statusDetails": {"message": "XFAIL Testing...\n\nValueError: TEST....", "trace": "self = <test_cases.example.test_mark.TestMark object at 0x000001B50FAA9820>\n\n    @pytest.mark.xfail(reason=\"Testing...\", condition=1)\n    def test_1(self):\n>       raise ValueError(\"TEST....\")\nE       ValueError: TEST....\n\ntest_cases\\example\\test_mark.py:15: ValueError"}, "start": 1679024001923, "stop": 1679024001923, "uuid": "671319d0-8c77-42a1-8fcf-dce00bb8506b", "historyId": "c072a24f35d714334440ae14c480421f", "testCaseId": "299ee004a0fd0a9918738588ece61e24", "fullName": "test_cases.example.test_mark.TestMark#test_1", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Testing...', condition=1)"}, {"name": "parentSuite", "value": "test_cases.example"}, {"name": "suite", "value": "test_mark"}, {"name": "subSuite", "value": "TestMark"}, {"name": "host", "value": "DESKTOP-E380NSU"}, {"name": "thread", "value": "16728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.example.test_mark"}]}