{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10.0 != 10", "trace": "self = <test_cases.example.test_example.TestCases object at 0x000001B50FAA0A60>\n\n    @pytest.mark.usefixtures(\"foo\")\n    def test_02(self):\n        result = get_divid(1)\n>       assert result != 10\nE       assert 10.0 != 10\n\ntest_cases\\example\\test_example.py:39: AssertionError"}, "start": 1679024001515, "stop": 1679024001515, "uuid": "9151c523-8327-4795-bdee-1e5cf8384084", "historyId": "b08fc842579a084cd1c10ae008915f61", "testCaseId": "e69273178215ce8780107ceb09c3de50", "fullName": "test_cases.example.test_example.TestCases#test_02", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('foo')"}, {"name": "parentSuite", "value": "test_cases.example"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestCases"}, {"name": "host", "value": "DESKTOP-E380NSU"}, {"name": "thread", "value": "16728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.example.test_example"}]}