{"name": "test_44[4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (4 % 3) == 0", "trace": "self = <test_cases.example.test_mark.TestMark object at 0x000001B50FAB6040>, foo = 4\n\n    @pytest.mark.parametrize(\"foo\", [12,6,3,4])\n    def test_44(self, foo):\n        print(f\"test data: {foo}\")\n>       assert foo % 3 == 0\nE       assert (4 % 3) == 0\n\ntest_cases\\example\\test_mark.py:32: AssertionError"}, "parameters": [{"name": "foo", "value": "4"}], "start": 1679024001977, "stop": 1679024001978, "uuid": "93f4bd53-77bd-4aaf-88f2-e601f17ea674", "historyId": "63c07a508061df7f53fa27addcfcfaa5", "testCaseId": "2107b67f61d4f2abf2cc96c92f7ee8eb", "fullName": "test_cases.example.test_mark.TestMark#test_44", "labels": [{"name": "parentSuite", "value": "test_cases.example"}, {"name": "suite", "value": "test_mark"}, {"name": "subSuite", "value": "TestMark"}, {"name": "host", "value": "DESKTOP-E380NSU"}, {"name": "thread", "value": "16728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.example.test_mark"}]}